export const CONSTANTS = {
    FIELD_WIDTH:  767,
    FIELD_HEIGHT: 1152,

    START_Y_POSITION: -50,

    GOOSE_WIDTH: 62,
    GOOSE_HEIGHT: 32,
    GOOSE_FRAMES_COUNT: 7,

    CLOUD_WIDTH: 62,

    EXPLOSION_WIDTH: 82,
    EXPLOSION_HEIGHT: 78,
    EXPLOSION_FRAMES_COUNT: 6,

    AIRCRAFT_WIDTH: 90,
    AIRCRAFT_HEIGHT: 101,

    ENGINES_COUNT: 4,
    ENGINE_ALIVE_CLASSNAME: 'alive',
    ENGINE_DEAD_CLASSNAME: 'dead',

    TOP_SCORES_COUNT: 5,

    TOP_PLAYER_SCORE_INTERVAL: 1000,
    SCORE_INTERVAL: 1000,
};
